export const Coreteam = [
  {
    name: " Anubhav Madhav",
    position: "GDSC Lead",
    imgurl: "https://i.imgur.com/vI7JdZV.jpeg",
    githublink: "https://github.com/AnubhavMadhav",
    linkedinlink: "https://www.linkedin.com/in/anubhav-madhav/",
  },
  {
    name: "Kishan Dhakan",
    position: "Technical Writing Lead",
    imgurl: "https://i.imgur.com/ndDFvLK.jpeg",
    githublink: "https://github.com/Kishan-Dhakan",
    linkedinlink: "https://www.linkedin.com/in/kishan-dhakan-228bb5167",
  },
  {
    name: "Pushkar Patel",
    position: "Cloud Lead",
    imgurl: "https://i.imgur.com/MiVCFtP.jpeg",
    githublink: "https://github.com/thepushkarp",
    linkedinlink: "https://linkedin.com/in/thepushkarp/",
  },
  {
    name: "Raghvi Saxena",
    position: "Public Relations Lead",
    imgurl: "https://i.imgur.com/r2wDOFC.jpeg",
    githublink: "https://github.com/raghvisaxena",
    linkedinlink: "https://www.linkedin.com/in/raghvisaxena/",
  },
  {
    name: "Kapil Kumar",
    position: "Flutter Lead",
    imgurl: "https://i.imgur.com/QgIKorp.jpeg",
    githublink: "https://github.com/kapilkumar2001",
    linkedinlink: "https://www.linkedin.com/in/kapilkumar2001/",
  },
  {
    name: "Shivansh Kumar",
    position: "Web Dev Lead",
    imgurl: "https://i.imgur.com/koyPH6F.jpeg",
    githublink: "https://github.com/ShivanshKumar",
    linkedinlink: "https://www.linkedin.com/in/shivansh-kumar-248a751a0/",
  },
  {
    name: "Sahil Kundal",
    position: "Design Lead",
    imgurl: "https://i.imgur.com/Iezs6hX.jpeg",
    githublink: "https://www.behance.net/sahilkundal",
    linkedinlink: "https://www.linkedin.com/mwlite/in/sahil-kundal-725895192",
  },
  {
    name: "Aman Kothari",
    position: "Android Lead",
    imgurl: "https://i.imgur.com/IftDyzO.jpeg",
    githublink: "https://github.com/AmanKothari20",
    linkedinlink: "https://www.linkedin.com/in/aman-kothari-9b375319b/",
  },
  {
    name: "Samarth Singh",
    position: "AR/VR Lead",
    imgurl: "https://i.imgur.com/tfr818j.jpeg",
    githublink: "https://github.com/sam20code",
    linkedinlink: "https://www.linkedin.com/in/samarth-singh-56b5251b4/",
  },
  {
    name: "Divyam Solanki",
    position: "Design Lead",
    imgurl: "https://i.imgur.com/4T6P0Wg.jpeg",
    githublink: "https://github.com/solankidivyam",
    linkedinlink: "https://www.linkedin.com/in/divyam-solanki-7a9a12190/",
  },
  {
    name: "Aman Raj",
    position: "Web Lead",
    imgurl: "https://i.imgur.com/WZWXLb2.jpeg",
    githublink: "https://github.com/AmanRaj1608",
    linkedinlink: "https://www.linkedin.com/in/amanraj1608/",
  },
  {
    name: "Krishna Gaur",
    position: "ML/AI Lead",
    imgurl: "https://i.imgur.com/5IadY8b.jpeg",
    githublink: "https://github.com/gaurKrishna",
    linkedinlink: "https://www.linkedin.com/in/krishna-gaur/",
  },
  {
    name: "Ashutosh Singh",
    position: "Android Lead",
    imgurl: "https://i.imgur.com/kBWGbHA.jpeg",
    githublink: "https://github.com/thecodepapaya",
    linkedinlink: "https://www.linkedin.com/in/ashutoshsingh05as/",
  },
];
