export const Mentors = [
  {
    name: "Naman Kalra",
    position: "Blockchain Mentor",
    imgurl: 'https://i.imgur.com/ZTcsI5F.jpeg',
    githublink: "https://github.com/Naman-1234",
    linkedinlink: "https://www.linkedin.com/in/naman-kalra-9192571aa/",
  },
  {
    name: "Yash Shah",
    position: "Cloud Mentor",
    imgurl: 'https://i.imgur.com/NbjdzNb.jpeg',
    githublink: "https://github.com/theyashshahs/",
    linkedinlink: "https://www.linkedin.com/in/theyashshahs",
  },
  {
    name: "Darshan Hande",
    position: "Technical Writing Mentor",
    imgurl: 'https://i.imgur.com/Sqrrwri.jpeg',
    githublink: "https://github.com/darshanhande11",
    linkedinlink: "https://www.linkedin.com/in/darshan-hande-6a7479128",
  },
  {
    name: "Subhanjali Sharma",
    position: "UI/UX Mentor",
    imgurl: 'https://i.imgur.com/jtv1r5M.jpeg',
    githublink: "https://github.com/subhanjali",
    linkedinlink: "https://www.linkedin.com/in/subhanjali-sharma-9102511b2/",
  },
  {
    name: "Nitanshu Lokhande",
    position: "Open Source Mentor",
    imgurl: 'https://i.imgur.com/sMTIYl8.jpeg',
    githublink: "https://github.com/nlok5923",
    linkedinlink: "https://www.linkedin.com/in/nitanshu-lokhande-5b60691a0/",
  },
  {
    name: "Gulshan Patidar",
    position: "Android Mentor",
    imgurl: 'https://i.imgur.com/lA5qiNm.jpeg',
    githublink: "https://github.com/gulshanpatidar",
    linkedinlink: "https://www.linkedin.com/in/gulshan-patidar-8114821aa",
  },
  {
    name: "Keshav Agarwal",
    position: "Open Source Mentor",
    imgurl: 'https://i.imgur.com/Vi9hTRR.jpeg',
    githublink: "https://github.com/keshavagarwal17",
    linkedinlink: "https://www.linkedin.com/in/keshavagarwal1710/",
  },
  {
    name: "Aman Ghumra",
    position: "Web Dev Mentor",
    imgurl: 'https://i.imgur.com/ZuuLDAX.jpeg',
    githublink: "https://github.com/Aman7127",
    linkedinlink: "https://www.linkedin.com/in/aman-ghumra-491031205/",
  },
  {
    name: "Abhijeet Tamrakar",
    position: "DSA Mentor",
    imgurl: 'https://i.imgur.com/gLG5HQG.jpeg',
    githublink: "https://github.com/mrcchef",
    linkedinlink: "https://www.linkedin.com/in/abhijeettamrakar/",
  },
  {
    name: "Himanshu Mishra",
    position: "Web Dev Mentor",
    imgurl: 'https://i.imgur.com/vrGCuqe.jpeg',
    githublink: "https://github.com/Himanshu44626748",
    linkedinlink: "https://www.linkedin.com/in/himanshu-mishra-a2a4801aa/",
  },  {
    name: "Abhinav Gupta",
    position: "ML/AI Mentor",
    imgurl: 'https://i.imgur.com/n3rQr3R.jpeg',
    githublink: "https://github.com/Abhinav1299",
    linkedinlink: "https://www.linkedin.com/in/abhinav-gupta-933825180/",
  },  {
    name: "Amitvikram Dwivedi",
    position: "Web Dev Mentor",
    imgurl: 'https://i.imgur.com/wO7eEnM.jpeg',
    githublink: "https://github.com/batflarrow/",
    linkedinlink: "https://www.linkedin.com/in/amitbatflarrow/",
  },  {
    name: "Akshat Dobriyal",
    position: "Blockchain Mentor",
    imgurl: 'https://i.imgur.com/6TxGZsG.jpeg',
    githublink: "https://github.com/AkshatDobriyal",
    linkedinlink: "https://www.linkedin.com/in/akshat-dobriyal-b1aa7a200/",
  },  {
    name: "Kshittiz Bhardwaj",
    position: "Flutter mentor",
    imgurl: 'https://i.imgur.com/BOwesLk.jpeg',
    githublink: "https://github.com/Kshittiz21",
    linkedinlink: "https://www.linkedin.com/in/kshittiz-bhardwaj-60ab88187/",
  }, 

  {
    name: "Sanjay Prajapati",
    position: "Open Source Mentor",
    imgurl: 'https://i.imgur.com/sUPWKtf.jpeg',
    githublink: "https://github.com/sanjay270899",
    linkedinlink: "https://www.linkedin.com/in/sanjay270899",
  }, {
    name: "Rahul Bansal",
    position: "Open Source Mentor",
    imgurl: 'https://i.imgur.com/M98bUpM.jpeg',
    githublink: "https://github.com/RahulBansal0502",
    linkedinlink: "https://www.linkedin.com/in/rahulbansal52/",
  }, 

  {
    name: "Nishant Andoriya",
    position: "Flutter Mentor",
    imgurl: 'https://i.imgur.com/YhjDgfD.jpeg',
    githublink: "https://github.com/M-A-D-A-R-A",
    linkedinlink: "https://www.linkedin.com/in/nishant-andoriya-831727199/",
  }, 

  {
    name: "Dev Parmar",
    position: "ML/AI Mentor",
    imgurl: 'https://i.imgur.com/1OwJhe0.jpeg',
    githublink: "https://github.com/devparmar1",
    linkedinlink: "https://www.linkedin.com/in/dev-parmar",
  }, 
  {
    name: "Goutham Kundena",
    position: "Cyber Security Mentor",
    imgurl: 'https://i.imgur.com/ypKMafh.jpeg',
    githublink: "https://github.com/KGoutham7214",
    linkedinlink: "https://www.linkedin.com/in/goutham-kundena-80244a222",
  }, 
  {
    name: "Sameer Anand",
    position: "Technical Writing Mentor",
    imgurl: 'https://i.imgur.com/kmYk4Le.jpeg',
    githublink: "https://github.com/sameeranand12",
    linkedinlink: "https://www.linkedin.com/in/sameeranand12/",
  }, 
];
