export const Volunteers = [
  {
    name: "Mohammad Amber Rizvi",
    position: "Flutter Volunteer",
    imgurl: 'https://i.imgur.com/LzXHkGt.jpeg',
    githublink: "https://github.com/marizvi",
    linkedinlink: "https://www.linkedin.com/in/mohd-amber-rizvi-93a55a201/",
  },
  {
    name: "Madhur Gupta",
    position: "Web Dev Volunteer",
    imgurl: 'https://i.imgur.com/E0BczAP.jpeg',
    githublink: "https://github.com/AmanKothari20",
    linkedinlink: "https://www.linkedin.com/in/aman-kothari-9b375319b/",
  },
  
  {
    name: "Dhruv Dave",
    position: "Web Dev Volunteer",
    imgurl: 'https://i.imgur.com/TTVwCbM.jpeg',
    githublink: "https://github.com/DhruvDave12",
    linkedinlink: "https://www.linkedin.com/in/dhruv1201/",
  },
  {
    name: "Kewal Delhiwala",
    position: "Open Source Volunteer",
    imgurl: 'https://i.imgur.com/fpBkSu9.jpeg',
    githublink: "https://github.com/kewal-wq",
    linkedinlink: "https://www.linkedin.com/in/kewal-delhiwala-a4ba24201",
  },
  {
    name: "Parth Chandravadiya",
    position: "UI/UX Volunteer",
    imgurl: 'https://i.imgur.com/YEDAzxF.jpeg',
    githublink: "https://github.com/ParthChandravadiya",
    linkedinlink: "http://www.linkedin.com/in/parth-chandravadiya-0379a0227",
  },
  {
    name: "Tushar Vyas",
    position: "DSA Volunteer",
    imgurl: 'https://i.imgur.com/9tbhAk8.jpeg',
    githublink: "https://github.com/Tusharv0607",
    linkedinlink: "https://www.linkedin.com/in/tushar-vyas-67353021b/",
  },
  {
    name: "Tushar agrawal",
    position: "Android volunteer",
    imgurl: 'https://i.imgur.com/tiF5yZL.jpeg',
    githublink: "https://github.com/TusharAgrawal07",
    linkedinlink: "https://www.linkedin.com/in/tushar-agrawal-401913206",
  },
  {
    name: "Tirth Joshi",
    position: "Open Source Volunteer",
    imgurl: 'https://i.imgur.com/4jijt3J.jpeg',
    githublink: "https://github.com/tirth5828",
    linkedinlink: "https://www.linkedin.com/in/tirth5828",
  },
  {
    name: "Nitya Patel",
    position: "ML/AI Volunteer",
    imgurl: 'https://i.imgur.com/x9R4mYe.jpeg',
    githublink: "https://github.com/nityapatel19",
    linkedinlink: "https://www.linkedin.com/in/nityapatel19",
  },  {
    name: "Ankur Kumar Shukla",
    position: "ML/AI Volunteer",
    imgurl: 'https://i.imgur.com/eVQLYO2.jpeg',
    githublink: "https://github.com/AnkurKumarShukla",
    linkedinlink: "https://www.linkedin.com/in/ankur-kumar-shukla-3581b11b8",
  },  {
    name: "Pushkaraj Rajaram Kolekar",
    position: "Cloud Volunteer",
    imgurl: 'https://i.imgur.com/YrI6Yg0.jpeg',
    githublink: "https://github.com/2pushkaraj3",
    linkedinlink: "https://www.linkedin.com/in/pushkaraj-kolekar-5544841bb",
  },  {
    name: "Foram Talpada",
    position: "Android Volunteer",
    imgurl: 'https://i.imgur.com/gJMENt5.jpeg',
    githublink: "https://github.com/foram-patel-0201",
    linkedinlink: "https://www.linkedin.com/in/foram-talpada-9a0686228",
  },
  {
    name: "Bhavsar Yashesh Sameer",
    position: "Flutter Volunteer",
    imgurl: 'https://i.imgur.com/2PwXBUz.jpeg',
    githublink: "https://github.com/yashesh07",
    linkedinlink: "https://www.linkedin.com/in/yashesh-bhavsar-a163541b7/",
  }, {
    name: "Riya Parikh",
    position: "Web Dev Volunteer",
    imgurl: 'https://i.imgur.com/oi6nBQn.jpeg',
    githublink: "https://github.com/RiyaParikh0112",
    linkedinlink: "https://www.linkedin.com/in/riya-parikh-27b345196/",
  }, {
    name: "Dhruv Rashiya",
    position: "Web Dev Volunteer",
    imgurl: 'https://i.imgur.com/MLKreGH.jpeg',
    githublink: "https://github.com/rashiyadhruv",
    linkedinlink: "https://www.linkedin.com/in/dhruv-rashiya-6164791b8/",
  }, {
    name: "Akhilesh Manda",
    position: "Flutter Volunteer",
    imgurl: 'https://i.imgur.com/ncTYFcB.jpeg',
    githublink: "https://github.com/AkhileshManda",
    linkedinlink: "https://www.linkedin.com/in/akhilesh-manda-7a9b661b8/",
  },

  {
    name: "Yash Borikar",
    position: "Cloud Volunteer",
    imgurl: 'https://i.imgur.com/Q8LAmj2.jpeg',
    githublink: "https://github.com/borikaryash",
    linkedinlink: "https://www.linkedin.com/in/borikaryash/",
  },

  {
    name: "Aman Gangwar",
    position: "ML/AI Volunteer",
    imgurl: 'https://i.imgur.com/vtZy4aQ.jpeg',
    githublink: "https://github.com/iamangangwar",
    linkedinlink: "https://www.linkedin.com/in/iamangangwar/",
  },

  {
    name: "Harsh Mehta",
    position: "Blockchain Volunteer",
    imgurl: 'https://i.imgur.com/YxN6X0z.jpeg',
    githublink: "https://github.com/harsh-2O",
    linkedinlink: "https://www.linkedin.com/in/harshmehta2318/",
  },
  {
    name: "Kalash Kala",
    position: "DSA Volunteer",
    imgurl: 'https://i.imgur.com/IVsTHZa.jpeg',
    githublink: "https://github.com/kalash-kala",
    linkedinlink: "https://www.linkedin.com/in/kalash-kala-477b701ba/",
  },
  {
    name: "Hritik Kumar",
    position: "DSA Volunteer",
    imgurl: 'https://i.imgur.com/oThvI9b.jpeg',
    githublink: "https://github.com/hritik01478",
    linkedinlink: "http://www.linkedin.com/in/hritik01478",
  },
];
